### ISSUE TITLE
Question: How to find subdomain?

### ISSUE THREAD

**Issue by Kaizen86** [JakeMakesStuff/smhw.py#2]
In order to use this module, it requires a subdomain. (among other things).
I know what the school ID is, but there doesn't appear to be a subdomain in the URL. (`https://www.showmyhomework.co.uk/todos/issued`)
If there is a subdomain but is hidden somewhere, where can I find it?
Sorry if this is a stupid question.

**Comment by corpm014** [comment]
Hi there,
Maybe this can help?
https://gist.github.com/fourohfour/ccb010776c8a8157f597501bb55fde66

**Comment by corpm014** [comment]
It isn't actually based on this specific showmyhomework module, but it uses the same API so I guess it might work.

**Comment by corpm014** [comment]
Try entering this to your browser 'myschool.showmyhomework.co.uk', and instead change 'myschool' into your school name and if it responses without an error, you can use the name that you put in myschool for the subdomain.

**Comment by Kaizen86** [comment]
I forgot I asked this question two years ago, oops
